import { ColorPalette } from '@/types/pixel-converter';

export const WPLACE_COLOR_PALETTE: ColorPalette[] = [
  // Free colors
  { name: 'Black', hex: '#000000', isPremium: false },
  { name: 'White', hex: '#FFFFFF', isPremium: false },
  { name: 'Dark Gray', hex: '#3C3C3C', isPremium: false },
  { name: 'Gray', hex: '#787878', isPremium: false },
  { name: 'Medium Gray', hex: '#AAAAAA', isPremium: false },
  { name: 'Light Gray', hex: '#D2D2D2', isPremium: false },
  { name: 'Red', hex: '#ED1C24', isPremium: false },
  { name: 'Orange', hex: '#FF7F27', isPremium: false },
  { name: 'Yellow', hex: '#F9DD3B', isPremium: false },
  { name: 'Green', hex: '#13E67B', isPremium: false },
  { name: 'Blue', hex: '#4093E4', isPremium: false },
  { name: 'Purple', hex: '#AA38B9', isPremium: false },
  { name: 'Brown', hex: '#95682A', isPremium: false },
  
  // Premium colors
  { name: 'Deep Red', hex: '#600018', isPremium: true },
  { name: 'Dark Red', hex: '#A50E1E', isPremium: true },
  { name: 'Light Red', hex: '#FA8072', isPremium: true },
  { name: 'Dark Orange', hex: '#E45C1A', isPremium: true },
  { name: 'Gold', hex: '#F6AA09', isPremium: true },
  { name: 'Light Yellow', hex: '#FFFABC', isPremium: true },
  { name: 'Dark Goldenrod', hex: '#9C8431', isPremium: true },
  { name: 'Goldenrod', hex: '#C5AD31', isPremium: true },
  { name: 'Light Goldenrod', hex: '#E8D45F', isPremium: true },
  { name: 'Dark Olive', hex: '#4A6B3A', isPremium: true },
  { name: 'Olive', hex: '#5A944A', isPremium: true },
  { name: 'Light Olive', hex: '#84C573', isPremium: true },
  { name: 'Dark Green', hex: '#0EB968', isPremium: true },
  { name: 'Light Green', hex: '#87FF5E', isPremium: true },
  { name: 'Dark Teal', hex: '#0C816E', isPremium: true },
  { name: 'Teal', hex: '#10AEA6', isPremium: true },
  { name: 'Light Teal', hex: '#13E1BE', isPremium: true },
  { name: 'Dark Cyan', hex: '#0F799F', isPremium: true },
  { name: 'Cyan', hex: '#60F7F2', isPremium: true },
  { name: 'Light Cyan', hex: '#BBFAF2', isPremium: true },
  { name: 'Dark Blue', hex: '#28509E', isPremium: true },
  { name: 'Light Blue', hex: '#7DC7FF', isPremium: true },
  { name: 'Dark Indigo', hex: '#4D31B8', isPremium: true },
  { name: 'Indigo', hex: '#6B50F6', isPremium: true },
  { name: 'Light Indigo', hex: '#99B1FB', isPremium: true },
  { name: 'Dark Slate Blue', hex: '#4A4284', isPremium: true },
  { name: 'Slate Blue', hex: '#7A71C4', isPremium: true },
  { name: 'Light Slate Blue', hex: '#B5AEF1', isPremium: true },
  { name: 'Dark Purple', hex: '#780C99', isPremium: true },
  { name: 'Light Purple', hex: '#E09FF9', isPremium: true },
  { name: 'Dark Pink', hex: '#CB007A', isPremium: true },
  { name: 'Pink', hex: '#EC1F80', isPremium: true },
  { name: 'Light Pink', hex: '#F38DA9', isPremium: true },
  { name: 'Dark Peach', hex: '#9B5249', isPremium: true },
  { name: 'Peach', hex: '#D18078', isPremium: true },
  { name: 'Light Peach', hex: '#FAB6A4', isPremium: true },
  { name: 'Dark Brown', hex: '#684634', isPremium: true },
  { name: 'Light Brown', hex: '#DBA463', isPremium: true },
  { name: 'Dark Tan', hex: '#7B6352', isPremium: true },
  { name: 'Tan', hex: '#9C846B', isPremium: true },
  { name: 'Light Tan', hex: '#D6B594', isPremium: true },
  { name: 'Dark Beige', hex: '#D18051', isPremium: true },
  { name: 'Beige', hex: '#F8B277', isPremium: true },
  { name: 'Light Beige', hex: '#FFC5A5', isPremium: true },
  { name: 'Dark Stone', hex: '#6D643F', isPremium: true },
  { name: 'Stone', hex: '#948C6B', isPremium: true },
  { name: 'Light Stone', hex: '#CDC59E', isPremium: true },
  { name: 'Dark Slate', hex: '#333941', isPremium: true },
  { name: 'Slate', hex: '#6D758D', isPremium: true },
  { name: 'Light Slate', hex: '#B3B9D1', isPremium: true },
];

export const getFreeColors = () => WPLACE_COLOR_PALETTE.filter(color => !color.isPremium);
export const getPremiumColors = () => WPLACE_COLOR_PALETTE.filter(color => color.isPremium);